'use strict';

/**
 * Security Report Generator.
 *
 * Reporting is the deliverable a client actually pays for, so this module turns
 * a structured finding into a professional artifact in two formats:
 *   - POST /api/reports/markdown  -> returns a downloadable .md file
 *   - POST /api/reports/pdf       -> returns a downloadable .pdf (via PDFKit)
 *
 * The Markdown structure mirrors the layout used in real penetration-testing
 * reports (finding metadata, CVSS, reproduction, PoC, risk, remediation).
 */

const express = require('express');
const PDFDocument = require('pdfkit');

const router = express.Router();

/**
 * Normalise and lightly validate the submitted finding.
 * We never throw on missing fields — a report with "N/A" placeholders is more
 * useful to a learner than a 400 error.
 */
function normalizeFinding(body = {}) {
  const str = (v, fallback = 'N/A') => {
    const s = (v === undefined || v === null ? '' : String(v)).trim();
    return s.length ? s : fallback;
  };
  const cvss = Number(body.cvssScore);
  return {
    title: str(body.title, 'Untitled Finding'),
    category: str(body.category),
    severity: str(body.severity, 'Informational'),
    cvssScore: Number.isFinite(cvss) ? Math.min(10, Math.max(0, cvss)) : null,
    affectedComponent: str(body.affectedComponent),
    description: str(body.description),
    stepsToReproduce: str(body.stepsToReproduce),
    proofOfConcept: str(body.proofOfConcept),
    riskAssessment: str(body.riskAssessment),
    remediation: str(body.remediation),
    reporter: str(body.reporter, 'Anonymous Researcher'),
    // Timestamp is provided by the client so the server stays stateless/pure;
    // fall back to an ISO string generated here if the client omitted it.
    date: str(body.date, new Date().toISOString().slice(0, 10))
  };
}

/** Map a CVSS base score to its qualitative severity band (CVSS v3.1). */
function cvssBand(score) {
  if (score === null) return 'Unrated';
  if (score === 0) return 'None';
  if (score < 4.0) return 'Low';
  if (score < 7.0) return 'Medium';
  if (score < 9.0) return 'High';
  return 'Critical';
}

/** Build the Markdown document from a normalised finding. */
function buildMarkdown(f) {
  const cvssLine =
    f.cvssScore === null
      ? '**CVSS Base Score:** N/A'
      : `**CVSS Base Score:** ${f.cvssScore.toFixed(1)} (${cvssBand(f.cvssScore)})`;

  return `# Security Assessment Report

> **Confidential — White Hat Lab (Educational)**
> This report was produced inside a local training environment and describes a
> simulated finding for learning purposes only.

**Finding:** ${f.title}
**Prepared by:** ${f.reporter}
**Date:** ${f.date}

---

## 1. Summary

| Field | Value |
| --- | --- |
| Vulnerability Title | ${f.title} |
| Category | ${f.category} |
| Severity | ${f.severity} |
| CVSS Base Score | ${f.cvssScore === null ? 'N/A' : f.cvssScore.toFixed(1) + ' (' + cvssBand(f.cvssScore) + ')'} |
| Affected Component | ${f.affectedComponent} |

${cvssLine}

## 2. Description

${f.description}

## 3. Affected Component

${f.affectedComponent}

## 4. Steps to Reproduce

${f.stepsToReproduce}

## 5. Proof of Concept

\`\`\`
${f.proofOfConcept}
\`\`\`

## 6. Risk Assessment

${f.riskAssessment}

## 7. Remediation Recommendations

${f.remediation}

---

*Generated by White Hat Lab — a local, educational cybersecurity training platform.*
`;
}

/** Turn a title into a safe file name stem. */
function slugify(title) {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'security-report'
  );
}

// ---- Markdown endpoint ------------------------------------------------------
router.post('/markdown', (req, res) => {
  const finding = normalizeFinding(req.body);
  const md = buildMarkdown(finding);
  const filename = `${slugify(finding.title)}.md`;

  res
    .type('text/markdown')
    .set('Content-Disposition', `attachment; filename="${filename}"`)
    .send(md);
});

// ---- PDF endpoint (PDFKit — pure JS, no native deps) ------------------------
router.post('/pdf', (req, res) => {
  const f = normalizeFinding(req.body);
  const filename = `${slugify(f.title)}.pdf`;

  const doc = new PDFDocument({ size: 'A4', margin: 56 });
  res
    .type('application/pdf')
    .set('Content-Disposition', `attachment; filename="${filename}"`);
  doc.pipe(res);

  const ACCENT = '#2563eb';
  const MUTED = '#555555';

  const h1 = (t) => doc.moveDown(0.6).fillColor(ACCENT).fontSize(20).font('Helvetica-Bold').text(t);
  const h2 = (t) => doc.moveDown(0.6).fillColor('#111111').fontSize(13).font('Helvetica-Bold').text(t);
  const body = (t) => doc.moveDown(0.2).fillColor('#222222').fontSize(10.5).font('Helvetica').text(t, { align: 'left' });
  const meta = (label, value) =>
    doc.moveDown(0.1).fontSize(10.5).fillColor(MUTED).font('Helvetica-Bold').text(label + '  ', { continued: true })
      .fillColor('#111111').font('Helvetica').text(value);

  // Header
  doc.fillColor('#111111').fontSize(24).font('Helvetica-Bold').text('Security Assessment Report');
  doc.moveDown(0.2).fontSize(10).fillColor(MUTED).font('Helvetica')
    .text('Confidential — White Hat Lab (Educational). Simulated finding for local training only.');
  doc.moveDown(0.4);
  doc.strokeColor('#dddddd').moveTo(doc.x, doc.y).lineTo(doc.page.width - 56, doc.y).stroke();

  h1(f.title);
  meta('Prepared by:', f.reporter);
  meta('Date:', f.date);

  h2('1. Summary');
  meta('Category:', f.category);
  meta('Severity:', f.severity);
  meta('CVSS Base Score:', f.cvssScore === null ? 'N/A' : `${f.cvssScore.toFixed(1)} (${cvssBand(f.cvssScore)})`);
  meta('Affected Component:', f.affectedComponent);

  h2('2. Description');
  body(f.description);
  h2('3. Steps to Reproduce');
  body(f.stepsToReproduce);
  h2('4. Proof of Concept');
  doc.moveDown(0.2).font('Courier').fontSize(9.5).fillColor('#0b3d0b').text(f.proofOfConcept);
  h2('5. Risk Assessment');
  body(f.riskAssessment);
  h2('6. Remediation Recommendations');
  body(f.remediation);

  doc.moveDown(1);
  doc.fontSize(8.5).fillColor(MUTED).font('Helvetica')
    .text('Generated by White Hat Lab — a local, educational cybersecurity training platform.', { align: 'center' });

  doc.end();
});

// ---- Live Markdown preview (JSON in -> markdown string out, no download) ----
router.post('/preview', (req, res) => {
  res.json({ markdown: buildMarkdown(normalizeFinding(req.body)) });
});

module.exports = router;
